### ISSUE TITLE
Napalm Mummies

### ISSUE THREAD

**Issue by Bartholomue** [StardewModders/mod-ideas#1017]
I keep expecting that if I wear a napalm ring and kill a mummy, it'll blow up when I kill it. Instead, I still have to bomb it. Would it be possible to make a mod that lets mummies blow up when killed if the player is wearing a napalm ring?

**Comment by arphox** [comment]
I'm thinking about how this could be implemented.

My findings so far:
- there are no events related to combat
- so far I couldn't find any event that would fire when a mummy is knocked down (to have it killed if the player has a napalm ring)
- I was trying to find a way to get the list of NPCs so I could compare it between ticks to find distinguished knocked down mummies, but no success so far.

**Comment by arphox** [comment]
> I keep expecting that if I wear a napalm ring and kill a mummy, it'll blow up when I kill it

I was thinking about this.

While checking the source code for Mummy, I learned that the source code handles this Mummy specialty as if you wouldn't kill the monster.

Let me explain:

When a Mummy takes damage, the following happens, in order:
- if it is currently _reviving_, kill it if the damage is coming from a bomb, otherwise take no damage
- (do hit/miss calculation, doesn't matter here)
- take damage, and if you would kill it, it doesn't die, but instead:
  - its health is restored to full and
  - a 10 seconds revive timer is set and
  - a death animation is played

So _technically_ the mummy does not _die_ when you reduce its Health to below zero, but it is **knocked down** (the wiki uses this phrasing and I think it fits).

This is why the Napalm Ring does not work with the mummy, and since:
- I think this is fine like this (it makes sense) and
- the SMAPI does not provide an easy way to implement this,
I won't implement this, sorry.

But at least I did some digging that would be helpful for someone else that would implement this.

**Comment by aedenthorn** [comment]
I made a mod that does this, I can publish it soon

**Comment by aedenthorn** [comment]
https://www.nexusmods.com/stardewvalley/mods/15933/

**Comment by aedenthorn** [comment]
It's just the standard napalm ring explosion, so has the same effect.
