### ISSUE TITLE
Mines/Skull cavern Floor indicator relocation

### ISSUE THREAD

**Issue by Stuicide** [StardewModders/mod-ideas#1023]
A simple mod allowing someone to relocate the "Floor indicator" while in the Skull Caverns/Mines.

It's out of place and causes clashing aesthetic issues with other mods like Realtime Minimap/ Experience Bars mods.

Image for reference. https://ibb.co/rdf2DRn

**Comment by MindMeltMax** [comment]
[MoveMineLevel.zip](https://github.com/StardewModders/mod-ideas/files/10146839/MoveMineLevel.zip)
[MoveMineLevel Source.zip](https://github.com/StardewModders/mod-ideas/files/10146840/MoveMineLevel.Source.zip)
This should do it, there is also a config in case you want to tweak the position.
I also attached the source since I don't really plan on posting/maintaining this, but you're free to do so if you want
