### ISSUE TITLE
Mod list export

### ISSUE THREAD

**Issue by chronosh** [StardewModders/mod-ideas#1079]
Export a list of mods to share without using a mod manager.

**Comment by arphox** [comment]
Could you elaborate this idea, please?

If I'm correct, you can easily export your mods by packing/compressing your `Mods` (or equivalent) folder, and sending it to someone, who can unpack them and paste into their Mods folder. Would you like to make this method easier?

Or maybe you only want to export only the (unique identifier) **name** and **version** of the mods you are using?

You mentioned only exporting, but also sharing, too. How about importing? Did you think about that, too?

**Comment by arphox** [comment]
I'm thinking about whether this should be a **mod** at all.

Since thisinformation is on the file sytem anyways, a simple desktop app would do the trick, too, so the flow would look like:
- start the app
- it tries to automatically detect the stardew valley installation (but you can change that manually)
- it tries to automatically select the proper Mods folder (you may have multiple Mods folders, in that case it would require manual selection)
- click "export", and it displays the information you need in a text box, or writes it into a file, (or maybe clipboard but that's not that easy cross-platform AFAIK)

I would get the mod's name from the `manifest.json` file, using the `Name`, `Version` properties for name and version, and for the URL try to make sense of the `UpdateKeys` to identify where could it be downloaded from.

Example export idea:
```
Better Artisan Good Icons, Version: 1.5.0, URL: https://www.nexusmods.com/stardewvalley/mods/2080
Save Backup, Version: 3.18.2, URL: none
```

What do you think, how do you imagine this working?

**Comment by arphox** [comment]
@chronosh 

I have found a mod which basically does what we talked about:

[**Mod List Command**](https://www.nexusmods.com/stardewvalley/mods/5131)

Usage:
- install it as you would install a normal mod
- to export the list of mods, enter one of the following commands to the SMAPI console window:
  - `list_mods`
  - `list_mods csv "c:\Users\UserName\Desktop\mymods.csv"` or something like that to export it to a csv file

Example output from my testing:
```
list_mods
[Mod List] Mod List v1.1.1 by Blackclaw:
    - https://www.nexusmods.com/stardewvalley/mods/5131
Simple SMAPI command to list the installed mods to the console or a CSV file
[Mod List] Noclip Mode v1.3.6 by Pathoschild:
    - https://www.nexusmods.com/stardewvalley/mods/3900
Press a key to enable noclip mode (which lets you walk through anything).
[Mod List] Skip Intro v1.9.11 by Pathoschild:
    - https://www.nexusmods.com/stardewvalley/mods/533
Skips the game's loading intro.
[Mod List] TestMod v1.0.0 by Arphox:
    -
To try out stuff
[Mod List] Console Commands v3.18.2 by SMAPI:
    -
Adds SMAPI console commands that let you manipulate the game.
[Mod List] Error Handler v3.18.2 by SMAPI:
    -
Handles some common vanilla errors to log more useful info or avoid breaking the game.
[Mod List] Save Backup v3.18.2 by SMAPI:
    -
Automatically backs up all your saves once per day into its folder.
[Mod List] Fast Animations v1.11.4 by Pathoschild:
    - https://www.nexusmods.com/stardewvalley/mods/1089
Speeds up many animations in the game (configurable).
[Mod List] Generic Mod Config Menu v1.11.0 by spacechase0:
    - https://www.nexusmods.com/stardewvalley/mods/5098
Adds an in-game UI to edit other mods' config options (for mods which support it).
[Mod List] Running Late v1.2.0 by Coll1234567:
    - https://www.nexusmods.com/stardewvalley/mods/3518
Changes the digital clock on the HUD to update every in-game minute instead of every 10
```

If this solves your issue, use that mod and close this issue, please. :)

**Comment by chronosh** [comment]
Thank you so much, it's awesome!

**Comment by arphox** [comment]
@chronosh FYI I picked up the mod and updated it: fixed a bug, enhanced help text and console display.

https://www.nexusmods.com/stardewvalley/mods/5131

Enjoy!

This was my last message on this issue.
