### ISSUE TITLE
Mod idea: Configurable machine time & outputs

### ISSUE THREAD

**Issue by Yuemitsuri** [StardewModders/mod-ideas#163]
I know there's 2 mods that do that, that are out there, but it's broken/dead creators/not open source. Thus throwing the idea in.

Able to configure the time it takes to produce items and the outputs amount of it.
Thanks love!

**Comment by Pathoschild** [comment]
There's an [unofficial update for Machine Speed Change](https://mods.smapi.io/#Machine_Speed_Change) as of Stardew Valley 1.3.28, and the author might be willing to open-source it if asked. An open-source equivalent would be nice if not though.

**Comment by BayesianBandit** [comment]
Since this topic was opened, two open-source mods have been created that should fulfill most of the requested functionality. As far as I can tell, they are compatible with each other in-game.

- Mizzion's Configure Machine Outputs [[Nexus](https://www.nexusmods.com/stardewvalley/mods/3490), [GitHub](https://github.com/Mizzion/Configure-Machine-Outputs)]
- Bayesian's Configure Machine Speed [[Nexus](https://www.nexusmods.com/stardewvalley/mods/3519), [GitHub](https://github.com/BayesianBandit/ConfigureMachineSpeed)]

@Pathoschild @Yuemitsuri
