### ISSUE TITLE
cosmetic chests for all your organization needs

### ISSUE THREAD

**Issue by murachnid** [StardewModders/mod-ideas#202]
i had a few ideas already for it:
- trash cans (just for things categorized as trash, waiting to be thrown into the recycling machine)
- seed box (i actually have an issue with having too many seeds in my chests and being forced to make more chests due to it)
- thats honestly all i have, but i mostly just really wanted trash cans as chests

**Comment by KarBoy2314PL** [comment]
[Here's a mod that allows you to color any chest to any color, but making a new block that works like a chest is a different story](https://www.nexusmods.com/stardewvalley/mods/1623)

**Comment by KeepFireFlying** [comment]
Colorful chests isn't needed anymore since that's in the vanilla game now.
For the seed box, even if there was a new item that behaved as a chest for seeds (should that be restricted to seeds? Is that doable?), you'd need to "page through" the inventory screen since you don't want multiple chests/seed boxes. I wonder if Chests Anywhere could be utilized here with inaccessible chests acting as the storage mechanism...
Okay, so would this maybe be like adding a new item to the game that opens the Chests Anywhere interface, and Chests Anywhere would use some hidden chests for its natural functionality?

**Comment by KeepFireFlying** [comment]
I was making that way more complicated than it needs to be. I finished the trashcan.

**Comment by ImJustMatt** [comment]
Expanded Storages can be used to create custom chests that support all the features listed in the original request. Additionally one of the content packs for it is going through vanilla graphics and making them into craftable storages.

**Comment by KeepFireFlying** [comment]
> Expanded Storages can be used to create custom chests that support all the features listed in the original request. Additionally one of the content packs for it is going through vanilla graphics and making them into craftable storages.

Thanks! I pretty much forgot about this issue. >_>
