### ISSUE TITLE
Request: Artifact Digger/Finder Mod with configurable Auto-Dig Radius and MagneticRadius

### ISSUE THREAD

**Issue by Kevipro** [StardewModders/mod-ideas#204]
I know that some mods implement the Auto-Dig artifacts aspect. But they are not to my liking and seem a bit limited. As well as kind of broken (specifically) Limited"Joy of Efficiency" only allows 3 space radius to dig artifacts. and Broken "Foxyfficiency" which needs "StardewConfigMenu" to work properly. My Request is that I want a mod that will help locate the artifact spots and/or be able to dig them up to a hundred space Radius and the magnetic Radius to be adjusted to the same. And one more thing it would also be nice that this mod included the aspect of tree and bush shakers. To automatic collect those items.

**Comment by EpicBellyFlop45** [comment]
I'll start making this now

**Comment by Kevipro** [comment]
That's awesome. Thank you!!!

**Comment by Mizzion** [comment]
I know Epic said he would work on this, but since it's been so long and I was working on something similar for personal use, I've released something similar to this. It includes the bush and tree shaker, but they are set to false by default. You can change that by editing the config file,(You can do this while the game is running and then hit F5 to reload the config).

https://www.nexusmods.com/stardewvalley/mods/4212/
