### ISSUE TITLE
fishing reminder

### ISSUE THREAD

**Issue by Pookachutf** [StardewModders/mod-ideas#224]
I would love it if Willy would send a mail about what fish (player hasn't caught) are available based on weather/season

**Comment by OfficialRenny** [comment]
Oh damn this may be what gets me back into modding. This seems simple enough to do, will get on it 😃

**Comment by OfficialRenny** [comment]
Sorry for taking so long, have had a lot free time that I would have hoped to have.
https://github.com/OfficialRenny/WillyReminder
Here's the repo if anyone wants to do it with a head start, the base is pretty much done, just needs actual contents for the mail, and possibly mail for rainy day fish. Then maybe an array of all the fish and remove the ones that the player has caught.

**Comment by Mizzion** [comment]
Here you go, I would let the game run once so that the config file is generated, then you can change if you want a letter sent to you Daily, Weekly, Monthly. You can even set them all to true, and it should do the figuring out for you.

https://www.nexusmods.com/stardewvalley/mods/3615/

Source will be added to my git repo soon.
