### ISSUE TITLE
Add outdoor-themed furniture like gnomes and swings

### ISSUE THREAD

**Issue by 3-frogs** [StardewModders/mod-ideas#236]
Hi! I haven't found any mods for outside decoration specifically, I'd love to have more furniture with which decorate the farm (like more statues, decorative plants, benches, gnomes, maybe a fountain, a swing...) I thought of making it myself but I have no coding experience so this is a little overwhelming for me. I do have experience making pixel art though, so I'm willing (and excited!) to help out with textures.
It would be important that these aren't reskins but actual new items.

**Comment by KarBoy2314PL** [comment]
wouldn't be just easier to allow already existing furniture to be placed on the farm?

**Comment by Pathoschild** [comment]
This doesn't need any coding, since [Furniture Anywhere](https://www.nexusmods.com/stardewvalley/mods/2276) already lets you place furniture outside and [Custom Furniture](https://www.nexusmods.com/stardewvalley/mods/1254) can add new furniture.

So the scope of this ticket is really just creating content packs for Content Patcher (to replace existing furniture) or Custom Furniture (for new furniture), to add outdoor-themed furniture like gnomes and swings.

**Comment by 3-frogs** [comment]
Ah, thanks!! I'm gonna start working on it!

**Comment by KarBoy2314PL** [comment]
please don't close issues yourself, thank you

**Comment by EpicBellyFlop45** [comment]
Please don't reopen issues yourself, thank you
