### ISSUE TITLE
cooking recipes for using bugmeat

### ISSUE THREAD

**Issue by Traehgniw** [StardewModders/mod-ideas#281]
because it's only used for bait in game right now and people do in fact eat insects in real life :p

**Comment by KarBoy2314PL** [comment]
eww, geez, are we living in France or sth?

**Comment by Traehgniw** [comment]
Well the player character already canonically has no qualms about snails, considering escargot and strange buns are edible items, so giant bugs should probably also be on the menu :p

**Comment by Entoarox** [comment]
Bug Meat might simply be inedible because CA took out the meat & butcher systems, so I see no reason why it cant be done..

**Comment by BlatantDecoy** [comment]
Do you have any idea for what dishes could be made from bugmeat?

**Comment by BlatantDecoy** [comment]
I'm working on this using JA. Open to ideas.

**Comment by Traehgniw** [comment]
Honestly the only things I can think of right now are that cave gumbo, some kind of stirfry involving beans and bugmeat, bugmeat and chips, and like...meatloaf (2 bugmeat, 1 bread)

**Comment by BlatantDecoy** [comment]
I've got the following recipes lined up, if you'd like to help I need to figure out the buffs and the gift tastes. I'm probably going to have Jas, Vincent & Haley hate all Bugmeat Recipes as a standard.

- Cave Gumbo
- Bugmeat Ice Cream
- Bugmeatloaf
- Bugmeat Sandwich
- Bugmeat Broth
- Bugmeat & Chips

Also may take me longer than I thought as I want to explore options of unlocking recipes via Mail and Events rather than just buying them or knowing them by default.

**Comment by BlatantDecoy** [comment]
https://www.nexusmods.com/stardewvalley/mods/4502
Completed by me.
