### ISSUE TITLE
after JojoMarket fails ...

### ISSUE THREAD

**Issue by Antoninko** [StardewModders/mod-ideas#45]
so after jojomarket fails , i think it would be nice to have 3 options in what to turn it :
Option 1 : Turn it into a school so the kids can learn things.
Option 2 : Turn it into a hotel where the receptionist will be Shane
Option 3 : Destroy it and leave some free land 
There are no textures for now and i thing this will need smapi . i guess it will be pretty hard to do it too

**Comment by Warilized** [comment]
There's XNB mods (if i recall correctly) that do this, but you need to replace it manually after Jojomarket fails. there's no .dll mods present to automate this event.

To make .dll mods out of this, you may needs "Advanced Location Loader" if it's a whole new location (like Hotel, and School)

It'll be hard because we need textures for new location, but it opens a whole lot possibility in modding

**Comment by spacechase0** [comment]
Going to close this as vanilla does something with closed JojaMart now.
