### ISSUE TITLE
Better Leprechaun Shoes

### ISSUE THREAD

**Issue by TrentXV** [StardewModders/mod-ideas#456]
Make leprechaun shoes increase Luck.

**Comment by jamespfluger** [comment]
_As I am not a contributor I can't add a label, but this should have the needs info label_

@TrentXV I don't think would be too hard, but right now "increase Luck" is pretty vague. Are you looking for a small amount or a large   ##amount?

If I pick this up then I'll probably add a config file with a customizable value, but I'd have to determine what the default value would be.

#

The [wiki has some insight](https://stardewvalleywiki.com/Luck#Daily_Luck) into daily luck from the fortune teller. The [special charm](https://stardewvalleywiki.com/Special_Charm) increases it by 0.025 (if I'm reading it correctly), which is a rather small amount.

The temporary food buffs add an excessive amount to use as a default value.

**Comment by jamespfluger** [comment]
I'm going to pick this one up. I'll need to use Harmony to change the value of the daily luck, as the luck level itself is used infrequently in comparison. The config file will hold the default value, which will increase the daily luck value by a small amount by default. Likely ~10%

**Comment by jamespfluger** [comment]
[This is just a release candidate](https://github.com/jamespfluger/Stardew-ModCollection/releases/tag/1.0.0-LuckyBoots-rc.1), but I do have a working mod. Daily luck increases by 0.075 by default, which is 3x the amount of the special charm. This can be changed in the `config.json` file, which contains values for a multiplier and/or added value. It uses Harmony which isn't ideal and the mod could break in future updates, but it is a simple way to implement daily luck changes.

I know Minerva is working this issue as well, and it sounds like it'll be a better solution that mine because it won't be using Harmony (unlike mine). Minerva and someone else started work before me, so I won't be continuing my immediate development. However, I did want want to publish my work for anyone trying to learn how luck can be modified or consider a different approach than what they have so far.

**I won't be releasing this on Nexus, nor anywhere else, unless nobody else ends up releasing a mod for this.**

**Comment by minervamaga** [comment]
https://www.moddrop.com/stardew-valley/mods/752859-feeling-lucky

Complete!
