### ISSUE TITLE
Something to make me not depressed

### ISSUE THREAD

**Issue by scourge728** [StardewModders/mod-ideas#610]
it's self explanatory really

**Comment by Pathoschild** [comment]
Hi!

Creating mods can provide a sense of purpose and community, open new possibilities for the future, and let you peek under the hood more often (e.g. I often decompile games out of curiosity now). The learning curve can be steep if you don't have programming experience, but [we're happy to help](https://stardewvalleywiki.com/Modding:Community)! I've found that those can all help with depression, but each person is unique.

If you need help (or _especially_ if you feel you don't deserve help), I encourage you to call a local depression hotline. It can be reassuring to talk with someone who knows what it's like, and they can answer any questions and help find local resources.

I'll close this ticket since it's not a specific mod idea, but stay strong! You do matter.
