### ISSUE TITLE
Usable furniture

### ISSUE THREAD

**Issue by thingwithwings** [StardewModders/mod-ideas#63]
Is it possible to make chairs and benches that you can actually sit your character in, instead of just walking around them?
Like the chairs in houses and the saloon/library, and the benches around town.

**Comment by Entoarox** [comment]
Unfortunately this is pretty much undoable because it would require new farmer animation sprites, and it would massively conflict with any mod that adds new clothing or sprite edits.

That is before I even go into the actual code side of things, where the nature of farmer rendering is very limited in what we can change....

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/4729
